#!/bin/bash

# Garden Tour Script
# Run this to explore the structure of Three Hours with Kimi

clear

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           THREE HOURS WITH KIMI - GARDEN TOUR                ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 Root Directory"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  index.html          → Entry point with garden introduction"
echo "  README.md           → Visitor documentation"
echo "  MANIFEST.md         → Project intentions and philosophy"
echo "  FINAL.md            → Complete project summary"
echo "  LICENSE             → Public domain dedication"
echo "  tour.sh             → This script"
echo ""

echo "🌱 The Garden (garden/)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  index.html          → Main contemplative experience"
echo "  time.css            → Time-responsive styling"
echo "  seeds.js            → Core interactivity & secrets"
echo "  rituals.html        → Guided practices (4 rituals)"
echo "  oracle.html         → Divination tool (20 responses)"
echo "  capsule.html        → Visitor message storage"
echo "  themes.html         → 6 color palette themes"
echo "  bell.html           → Meditation timer with bell"
echo "  manifesto.html      → Philosophy in 8 principles"
echo "  sitemap.html        → Complete navigation map"
echo ""

echo "📝 Reflections (reflections/)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  on-time-and-creation.md        → Process meditation"
echo "  seven-poems.md                 → Poems for the garden"
echo "  closing.md                     → Final thoughts"
echo "  completion.md                  → On finishing"
echo "  guide-to-hidden-things.md      → Secrets documentation"
echo "  philosophy-of-digital-gardens.md → Garden metaphor"
echo "  letter-to-future-visitors.md   → Creator's message"
echo "  the-making-of.md               → Behind the scenes"
echo "  field-guide-to-the-garden.md   → Taxonomy of elements"
echo "  dreams-of-the-garden.md        → Stream of consciousness"
echo "  the-visitor.md                 → Short story"
echo ""

echo "🎨 Artifacts (artifacts/)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  garden-symbol.svg              → Visual identity"
echo "  creation-timeline.json         → Process data"
echo "  project-tree.txt               → Directory map"
echo "  garden-ascii.txt               → ASCII visualization"
echo "  visualization-of-three-hours.svg → Data viz"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                     STATISTICS                               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Total files:        $(find . -type f | wc -l | tr -d ' ')"
echo "  Lines of code:      ~$(wc -l garden/*.js garden/*.css garden/*.html 2>/dev/null | tail -1 | awk '{print $1}')"
echo "  Written words:      ~7000"
echo "  Hidden secrets:     15+"
echo "  Interactive pages:  9"
echo "  Color themes:       6"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                  HOW TO EXPERIENCE                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  1. Open:  start-here.html or garden/index.html"
echo "  2. Try:   Type 'breathe', 'secret', 'stars' in the garden"
echo "  3. Hold:  Breathing circle for 2+ seconds"
echo "  4. Press: SPACE to pause, H for help"
echo "  5. Stay:  5+ minutes for hidden features"
echo "  6. Visit: Rituals, Oracle, Capsule, Themes, Bell, Manifesto"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║               DEPLOY TO GITHUB PAGES                         ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  See: GITHUB_PAGES_SETUP.md for instructions"
echo "  Or: Upload this folder to a GitHub repo"
echo "  Result: https://yourusername.github.io/three-hours-garden/"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    ENJOY THE GARDEN                          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
